apiVersion: v1
kind: ServiceAccount
metadata:
  name: robin-operator
  labels:
    app.kubernetes.io/instance: robin
    app.kubernetes.io/managed-by: robin.io
    app.kubernetes.io/name: robin
  namespace: robinio