kind: Deployment
apiVersion: apps/v1
metadata:
  name: robincli
  namespace: default
  labels:
    name: robincli
spec:
  replicas: 1
  selector:
    matchLabels:
      name: robincli
  template:
    metadata:
      annotations:
        product: robin
      labels:
        name: robincli
    spec:
      containers:
      - name: robincli
        image: robineng/robinimg:5.4.8-154
        workingDir: /root
        command: ["/bin/bash","-c","mkdir -p /root/.robin; ln -s -t /usr/lib/python3.7/site-packages/ /opt/robin/current/python3/site-packages/robincli /opt/robin/current/python3/site-packages/stormgr_def.py /opt/robin/current/python3/site-packages/stormgr_lib.py; /opt/robin/current/bin/robin client add-context robin-master.robinio --set-current; while true; do sleep 10000; done"]
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
